### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by PowaBanga** [linux-minidisc/linux-minidisc#1]
Hi,
I want install linux-minidisc, but a recieve this error : 
"
lio@Karkatouf:~/linux-minidisc$ qmake -r
qmake: could not find a Qt installation of ''
"
I'm on ubuntu 13.10 AMD64. I Want install the logiciel from the git because with the deb from synaptic, the program run, can see my HIMD (not the NetMD), he can see the music on the HI-MD, but when I clic on "transfer", it nothing happens. I haven't answer from the terminal. :'( :'( :'(

With a Sony MD Walkman MZ-NH600

**Comment by glaubitz** [comment]
On 12/01/2013 10:05 PM, Hernou wrote:

> I'm on ubuntu 13.10, i Want install the logiciel from the git because
> with the deb from synaptic, the program run, can see my HIMD (not the
> NetMD), he can see the music on the HI-MD, but when I clic on
> "transfer", it nothing happens. I haven't answer from the terminal. :'(
> :'( :'(
> 
> With a Sony MD Walkman MZ-NH600

Transferring files from the device to your computer should work (using
the version available in Ubuntu 13.10 and onwards). Transferring files
to the device is currently not supported by the GUI. You can transfer
MP3 tracks using "himdcli" if you HiMD Walkman supports MP3 playback.

NetMD devices aren't supported by the graphical user interface
(QHiMDTransfer). You have to use the command line client
"netmdcli" for them.

**Comment by PowaBanga** [comment]
So for transfer a mp3 from pc to my MD walkman i should writte
"himdcli $HOME/MYMP3.mp3"
or 
"netmdcli $HOME/MYMP3.mp3"
or
"himdcli $HOME/MYFODERwithMP3s"

?

And what i should wirtte to extract the musics from the MD ?

**Comment by glaubitz** [comment]
On 12/01/2013 10:16 PM, Hernou wrote:

> So for transfer a mp3 from pc to my MD walkman i should writte
> "himdcli $HOME/MYMP3.mp3"
> or
> "netmdcli $HOME/MYMP3.mp3"

The manpages for "netmdcli" and "himdcli" should explain everything.

Transferring MP3s is not supported. They'd have to be converted
to ATRAC-LP first which is currently not possible due to lack
of decoder. Transferring them as WAV (PCM) files would work, but
that hasn't been implemented yet either.

Sorry for that!

**Comment by PowaBanga** [comment]
Does exist a way to convert audio file into ATRAC-LP ? 
What is the extention at the end of this files ? (like .mp3)

**Comment by glaubitz** [comment]
On 12/02/2013 12:47 AM, Hernou wrote:

> Does exist a way to convert audio file into ATRAC-LP ?
> What is the extention at the end of this files ? (like .mp3)

SonicStage is the only software capable of encoding ATRAC-LP.

Luckily, NetMD devices have a hardware encoder built-in. If you transfer
a WAV (PCM) file to the device, the NetMD Walkman will automatically
encode the file into ATRAC-SP or ATRAC-LP depending on what command
is sent to it.

However, we currently haven't implemented WAV transfers yet due to lack
of time. It's actually rather trivial to patch libnetmd to do that. But
since we have had so few users in the past, no one really currently has
the motivation to work on that.

**Comment by PowaBanga** [comment]
ho, if you do that, me i will use it every day ! :)

Can i record a wav into a net-md to extract it into ATRAC-XX and transfer it into my other HI-MD ?

I tried to send a wav into my md, and a recieve this :
netmdcli send /home/lio/Téléchargements/Emancipator/01.Anthem_Nym_Remix.wav
Error opening netmd
Error while opening the USB device
