### ISSUE TITLE
Why does an MD device require a 16bit/44.1khz input file for recording in SP mode?

### ISSUE THREAD

**Issue by aaronamm** [linux-minidisc/linux-minidisc#77]
Hello everyone.

According to my question in [netmd-js project](https://github.com/cybercase/netmd-js/issues/32) which [asivery](https://github.com/asivery) gave me very useful answers. 
However, we still don't know why a MD device requires a 16bit/44.1khz input file for recording in SP mode?

I would be glad if you could show me where to get this 16bit/44.1khz SP mode specification or how do you reverse engineer to get this input file's requirement.

Thank you.

**Comment by aaronamm** [comment]
CC @thp

**Comment by karcherm** [comment]
Data on MiniDisc always describes music sampled at the 44.1kHz, and has a dynamic range approximately equal to 16 linear PCM. The (classic) MD recorder does not contain a resampling unit, so it is unable to process audio data sampled at other rates than 44.1kHz. That's why a MD device requires a 44.1kHz input for recording SP tracks. The remaining question is: Why does the device require 16-bit LPCM as data format. We don't know for sure, but the MD recorder needs an ATRAC encoder anyway for recording audio data from the MIC input or received via S/P-DIF. Both the ADC as well as the S/P-DIF receiver present data in 16bit/44.1kHz linear PCM to the encoder. So it makes some sense that the PC is "just another recording source" providing data in the same format. Not requiring the data to be ATRAC encoded for SP recording also means that Sony can protect the intellectual property of their ATRAC-1 (SP) encoder by not providing a PC-based ATRAC-1 encoder.

**Comment by aaronamm** [comment]
@karcherm this very detailed and useful information. Thank you so much.
Just clarify other people "ADC" stands for analog to digital converter which is opposite to DAC (digital to analog converter).
